### PR TITLE
Includes a fairly comprehensive set of RELAXED html tags/attributes and ...

### PR DESCRIPTION
**Pull request by dvwright**
...allowed html entities

### CODE REVIEW

**Comment by trans** [comment]
Sorry, I've been pretty busy with other projects. I'll get to this ASAP.

**Comment by dvwright** [comment]
Sure, no worries. Only when you get time.

**Comment by trans** [comment]
Looks good. I take it I should merge this pull request and drop the former one?

**Comment by dvwright** [comment]
Yeah, ignore the first one.
The latest one is what I ended up using

**Pull request merged**
